services:
  starknet-agent-backend:
    build:
      context: .
      dockerfile: backend.dev.dockerfile
    volumes:
      - ./src:/home/starknet-agent/src
      - ./config.toml:/home/starknet-agent/config.toml
      - backend-dbstore:/home/starknet-agent/data
    ports:
      - 3001:3001
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - starknet-agent-network
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_HOSTED_MODE=true
    command: yarn run dev
    restart: unless-stopped

  starknet-agent-frontend:
    build:
      context: .
      dockerfile: app.dev.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
        - NEXT_PUBLIC_HOSTED_MODE=true
    volumes:
      - ./ui:/home/starknet-agent
      - /home/starknet-agent/node_modules
      - /home/starknet-agent/.next
    depends_on:
      - starknet-agent-backend
    ports:
      - 3000:3000
    networks:
      - starknet-agent-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: unless-stopped

  # docs-ingest:
  #   build:
  #     context: .
  #     dockerfile: ingest.dockerfile
  #   networks:
  #     - starknet-agent-network
  #   restart: 'no'

networks:
  starknet-agent-network:

volumes:
  backend-dbstore:
