services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - starknet-agent-network
    restart: unless-stopped

  starknet-agent-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    volumes:
      - backend-dbstore:/home/starknet-agent/data
    ports:
      - 3001:3001
    depends_on:
      - searxng
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - starknet-agent-network
    restart: unless-stopped

  starknet-agent-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
        - NEXT_PUBLIC_HOSTED_MODE=true
    depends_on:
      - starknet-agent-backend
    ports:
      - 3000:3000
    networks:
      - starknet-agent-network
    restart: unless-stopped

networks:
  starknet-agent-network:

volumes:
  backend-dbstore:
