[API_KEYS]
OPENAI = ""
GROQ = ""
ANTHROPIC = ""
DEEPSEEK = ""

[API_ENDPOINTS]
OLLAMA = ""
SEARXNG = "http://localhost:32768"

[CAIRO_DB]
MONGODB_URI = ""
DB_NAME = ""
COLLECTION_NAME = ""

[STARKNET_DB]
MONGODB_URI = ""
DB_NAME = ""
COLLECTION_NAME = ""

[ECOSYSTEM_DB]
MONGODB_URI = ""
DB_NAME = ""
COLLECTION_NAME = ""

[STARKNET_FOUNDRY_DB]
MONGODB_URI = ""
DB_NAME = ""
COLLECTION_NAME = ""

[GENERAL]
PORT = 3_001
SIMILARITY_MEASURE = "cosine"

[HOSTED_MODE]
DEFAULT_CHAT_PROVIDER = "anthropic"
DEFAULT_CHAT_MODEL = "Claude 3.5 Sonnet"
DEFAULT_EMBEDDING_PROVIDER = "openai"
DEFAULT_EMBEDDING_MODEL = "Text embedding 3 large"

[VERSIONS]
STARKNET_FOUNDRY = "0.35.0"
SCARB = "2.9.2"
